/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.ia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ali Zain
 */
public class Report2 extends javax.swing.JFrame {
    public static String url = "jdbc:mysql://localhost/funds?useSSL=false";
    public static String user = "root";
    public static String password = "";
    public static Connection con;
    public static Statement st;
    public static ResultSet rs;
    public static Connection conn;
    public static Statement sta;
    public static ResultSet res;
    public static DecimalFormat dc = new DecimalFormat(".##");

    /**
     * Creates new form Report2
     */
    public Report2() {
        initComponents();
        storeTable();
        sortTable();
    }
    
    public void sortTable()
    {
        DefaultTableModel dG = (DefaultTableModel) jTableReport2.getModel();
        TableRowSorter<DefaultTableModel> sort = new TableRowSorter<DefaultTableModel> (dG);
        jTableReport2.setRowSorter(sort);
        
        DefaultTableModel dT = (DefaultTableModel) jTableReport2Total.getModel();
        TableRowSorter<DefaultTableModel> sorts = new TableRowSorter<DefaultTableModel> (dT);
        jTableReport2Total.setRowSorter(sorts);
    }
    
    
    public void storeTable()
    {
        DefaultTableModel dSum = (DefaultTableModel) jTableReport2.getModel();
        DefaultTableModel dTot = (DefaultTableModel) jTableReport2Total.getModel();
        try
        {
            con = DriverManager.getConnection(url, user, password); 
            st = con.createStatement();
            String query = "SELECT divisions.divisionName, t1.numRequests, t1.tot_us, t1.tot_eu, t1.tot_sar FROM divisions LEFT OUTER JOIN (SELECT divCodeP, COUNT(*) AS numRequests, "
                    + "SUM(USDP) AS tot_us, SUM(EURP) AS tot_eu, SUM(SARP) AS tot_sar FROM costsMade GROUP BY divCodeP)t1 ON divisions.divisionCode=t1.divCodeP";
            rs = st.executeQuery(query); 
            while(rs.next())
            {
                double total = (rs.getDouble(3)*3.75) + (rs.getDouble(4)*4.35) + rs.getDouble(5);
                dSum.addRow(new Object[]{rs.getString(1), rs.getInt(2), rs.getDouble(3), rs.getDouble(4), rs.getDouble(5), dc.format(total)}); 
            }
            
            conn = DriverManager.getConnection(url, user, password);
            sta = conn.createStatement();
            String query2 = "SELECT t2.divisionName, costsMade.dateRequestedP, costsMade.dateArrangedP, costsMade.USDP, costsMade.EURP, costsMade.SARP, costsMade.completeP FROM costsMade "
                    + "LEFT OUTER JOIN (SELECT divisionCode, divisionName FROM divisions)t2 ON costsMade.divCodeP=t2.divisionCode";
            res = sta.executeQuery(query2); 
            while(res.next())
            {
                dTot.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getDouble(4), res.getDouble(5), res.getDouble(6), res.getBoolean(7)}); 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e); 
        }
        finally 
        {
            try
            {
                if (rs != null) 
                {
                    rs.close();
                }
                                
                if (st != null) 
                {
                    st.close();
                }
                
                if (con != null) 
                {
                    con.close();
                }
                
                if (res != null) 
                {
                    res.close();
                }
                                
                if (sta != null) 
                {
                    sta.close();
                }
                
                if (conn != null) 
                {
                    conn.close();
                }
            }
            catch(Exception exc)
            {
                JOptionPane.showMessageDialog(null, exc); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogoMain = new javax.swing.JLabel();
        jLMainTitle = new javax.swing.JLabel();
        jLSummaryHeading = new javax.swing.JLabel();
        jSeparatorMain = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReport2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReport2Total = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogoMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogoMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs/ia/download.png"))); // NOI18N
        jLogoMain.setMaximumSize(new java.awt.Dimension(300, 150));
        jLogoMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoMainMouseClicked(evt);
            }
        });
        getContentPane().add(jLogoMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 16, 369, 116));

        jLMainTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMainTitle.setText("Company Funds Paid");
        getContentPane().add(jLMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 884, 116));

        jLSummaryHeading.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLSummaryHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSummaryHeading.setText("Summary of Funds Disbursements");
        getContentPane().add(jLSummaryHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 601, -1));
        getContentPane().add(jSeparatorMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1292, 1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableReport2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Division", "Number of Requests", "USD", "EUR", "SAR", "Total in SAR"
            }
        ));
        jScrollPane1.setViewportView(jTableReport2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 260));

        jTabbedPane1.addTab("Overview", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableReport2Total.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Division", "Requested", "Arranged", "USD", "EUR", "SAR", "Complete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableReport2Total);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 260));

        jTabbedPane1.addTab("Full Details", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1270, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel dG = (DefaultTableModel) jTableReport2.getModel();
        DefaultTableModel dT = (DefaultTableModel) jTableReport2Total.getModel();
        dG.setRowCount(0);
        dT.setRowCount(0);
        storeTable();
    }//GEN-LAST:event_formWindowActivated

    private void jLogoMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoMainMouseClicked

    }//GEN-LAST:event_jLogoMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLMainTitle;
    private javax.swing.JLabel jLSummaryHeading;
    private javax.swing.JLabel jLogoMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorMain;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableReport2;
    private javax.swing.JTable jTableReport2Total;
    // End of variables declaration//GEN-END:variables
}
